language: php

php:
  - 5.5
  - 5.6
  - 7.0
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - travis_retry phpenv config-rm xdebug.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.0" "codeception/codeception:^2.0" "codeception/specify" "codeception/verify"
  - travis_retry composer install --prefer-source --no-interaction

# setup application:
  - |
    cp .env.dist .env
    sed -i s/yii2-starter-kit\.dev/localhost:8080/ .env

  - |
    composer exec codecept build -- -c tests/codeception/common
    composer exec codecept build -- -c tests/codeception/backend
    composer exec codecept build -- -c tests/codeception/frontend
    composer exec codecept build -- -c tests/codeception/console

before_script:
  - mysql -e 'CREATE DATABASE `yii2-starter-kit`;';
  - php tests/codeception/bin/yii app/setup --interactive=0

script:
  - |
    php -S localhost:8080 > /dev/null 2>&1 &
    composer run codecept build -- -c tests/codeception/common
    composer run codecept build -- -c tests/codeception/backend
    composer run codecept build -- -c tests/codeception/frontend
    composer run codecept build -- -c tests/codeception/console