sudo: true
dist: trusty

env:
  - COMPOSE_FILE=docker/travis.yml

services:
  - docker

# cache vendor dirs
cache:
  directories:
    - vendor

before_install:
  - docker-compose up --force-recreate -d

install:
  - cp .env.dist .env
  - sed -i s/yii2-starter-kit-test/yii2-starter-kit/ .env
  - docker-compose exec -T app composer install --dev --prefer-source --no-interaction
  - docker-compose exec -T app ./vendor/bin/codecept build
  - sleep 10 # waiting for mysql to start accepting connections

before_script:
  - docker-compose exec -T app php console/yii app/setup --interactive=0
  - docker-compose exec -T app php console/yii app/truncate --interactive=0

script:
  - docker-compose exec -T app php -S 127.0.0.1:8080 > /dev/null 2>&1 &
  - docker-compose exec -T app ./vendor/bin/codecept run --debug
