app:
  build: docker/php
  volumes:
    - ./docker/php/php.dev.ini:/usr/local/etc/php/php.ini
  environment:
    PHP_IDE_CONFIG: "serverName=docker"

db_test:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: yii2-starter-kit
    MYSQL_USER: ysk_dbu
    MYSQL_PASSWORD: ysk_pass